---

- name: configure | server
  lineinfile:
    dest: "{{ __nagios_server_nagios_cfg }}"
    backrefs: yes
    regexp: '#+(cfg_dir=/usr/local/nagios/etc/servers)[ \t]*'
    line: '\1'
  tags:
    - nagios
    - config
    - server

- name: configure | ensure server dir exists
  file:
    path: "{{ __nagios_server_servers_path }}"
    state: directory
    owner: "{{ nagios_server_user }}"
    group: "{{ nagios_server_user }}"
    mode: 0775
  tags:
    - nagios
    - config
    - server

- name: configure | ensure commands dir exits
  file:
    path: "{{ __nagios_server_commands_path }}"
    state: directory
    owner: "{{ nagios_server_user }}"
    group: "{{ nagios_server_user }}"
    mode: 0775
  tags:
    - nagios
    - config
    - server


- name: configure | add commands
  copy:
    dest: "{{ __nagios_server_commands_path }}/check_nrpe.cfg"
    src: "commands/{{ item }}"
    owner: "{{ nagios_server_user }}"
    group: "{{ nagios_server_user }}"
    mode: 0664
  with_items: nagios_server_additional_commands
  tags:
    - nagios
    - config
    - server
    - check_nrpe

- name: configure | include commands.d/*.cfg
  lineinfile:
    dest: "{{ __nagios_server_nagios_cfg }}"
    insertafter: 'cfg_file=(/[a-zA-Z0-9-_\.]+)+/templates.cfg'
    line: 'cfg_dir={{ __nagios_server_commands_path }}'
    state: present
  tags:
    - nagios
    - config
    - server

- name: configure | contacts
  template:
    src: contacts.cfg.j2
    dest: "{{ __nagios_server_contacts_cfg }}"
    owner: "{{ nagios_server_user }}"
    group: "{{ nagios_server_user }}"
    mode: 0640
  tags:
    - nagios
    - config
    - contacts
