---

- name: core | fetch
  sudo: no
  get_url:
    url: "{{ nagios_server_core_src_url }}"
    dest: "{{ __nagios_server_core_src_tarball_name }}"
    sha256sum: "{{ nagios_server_core_src_sha256 }}"
  tags:
    - nagios
    - core
    - fetch

- name: core | extract
  sudo: no
  command: >-
    tar xf {{ __nagios_server_core_src_tarball_name }}
  args:
    creates: "{{ __nagios_server_core_src_dir }}"
  tags:
    - nagios
    - core
    - extrace

- name: core | configure
  sudo: no
  command: >-
    ./configure \
      --with-nagios-group={{ nagios_server_user }} \
      --with-command-group={{ nagios_server_group }}
  args:
    chdir: "{{ __nagios_server_core_src_dir }}"
  tags:
    - nagios
    - core
    - configure

- name: core | build
  sudo: no
  command: make all
  args:
    chdir: "{{ __nagios_server_core_src_dir }}"
  tags:
    - nagios
    - core
    - build

- name: core | install
  command: "make {{ item }}"
  args:
    chdir: "{{ __nagios_server_core_src_dir }}"
  with_items:
    - install
    - install-commandmode
    - install-init
    - install-config
  tags:
    - nagios
    - core
    - install

- name: core | install-webconf
  command: >-
    /usr/bin/install \
      -c \
      -m 644 \
      sample-config/httpd.conf \
      {{ nagios_server_core_webconf_path }}
  args:
    chdir: "{{ __nagios_server_core_src_dir }}"
  notify: restart apache
  tags:
    - nagios
    - core
    - install
