---

- name: packages | update apt cache
  apt: update_cache=yes

- name: packages | install
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - apache2-utils
    - libapache2-mod-php5
    - php5-cgi
    - php5-gd
    - build-essential
    - libgd2-xpm-dev
    - openssl
    - libssl-dev
    - xinetd
    - unzip
    - python-passlib
  tags:
    - nagios
    - install
