---

- name: packages | install
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - apache2
    - build-essential
    - libgd2-xpm-dev
    - openssl
    - libssl-dev
    - xinetd
    - apache2-utils
    - unzip
  tags:
    - nagios
    - install
