---

- name: restart apache
  service:
    name: apache2
    state: restarted

- name: restart xinetd
  service:
    name: xinetd
    state: restarted

- name: start nagios
  service:
    name: nagios
    state: started
